# Generated by Django 3.2.19 on 2023-09-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20230914_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='thrapist',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='chat.userprofile')),
                ('title', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
