# Generated by Django 3.2.19 on 2023-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_thrapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(default='nurse', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='thrapist',
        ),
    ]
