# Generated by Django 3.2.19 on 2023-09-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20230915_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='representative_name',
        ),
    ]
