# Generated by Django 3.2.19 on 2023-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='representative_name',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
