# Generated by Django 3.2.19 on 2023-09-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='message_files/'),
        ),
    ]
