# Generated by Django 3.2.19 on 2023-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_message_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='message_files/'),
        ),
    ]
