# Generated by Django 3.2.19 on 2023-09-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_appointmentslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='chat/uploads/'),
        ),
    ]
