# Generated by Django 3.2.19 on 2023-09-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_alter_message_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/'),
        ),
    ]
