# Generated by Django 3.2.19 on 2023-09-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20230928_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='time_slot',
            field=models.CharField(choices=[('7:00 AM - 8:00 AM', '7:00 AM - 8:00 AM'), ('8:00 AM - 9:00 AM', '8:00 AM - 9:00 AM'), ('9:00 AM - 10:00 AM', '9:00 AM - 10:00 AM')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
