# Generated by Django 3.2.19 on 2023-09-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_auto_20230929_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentslot',
            name='therapist',
        ),
    ]
