# Generated by Django 3.2.19 on 2023-09-30 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_remove_appointmentslot_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='therapist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.userprofile'),
            preserve_default=False,
        ),
    ]
