# Generated by Django 3.2.19 on 2023-10-05 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_appointmentslot_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
