# Generated by Django 3.2.19 on 2023-10-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('finished', 'Finished')], default='draft', max_length=20),
        ),
    ]
