# Generated by Django 3.2.19 on 2023-10-14 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_appointment_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
