# Generated by Django 3.2.19 on 2023-10-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0032_alter_appointmentslot_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='my_service',
            field=models.CharField(choices=[('Counselor', 'Counselor'), ('Clinical Psychologist', 'Clinical Psychologist'), ('Psychiatrist', 'Psychiatrist')], default='Counselor', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='location',
            field=models.CharField(choices=[('Makerere University School of Psychology', 'Makerere University School of Psychology'), ('Makerere University School of Guidance & Counselling', 'Makerere University School of Guidance & Counselling'), ('Safe Places – Kyambogo', 'Safe Places – Kyambogo'), ('Makerere University Business School', 'Makerere University Business School')], default=False, max_length=100),
        ),
    ]
