# Generated by Django 3.2.19 on 2023-10-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0033_auto_20231018_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='my_service',
            field=models.CharField(choices=[('Counselor', 'Counselor'), ('Clinical Psychologist', 'Clinical Psychologist'), ('Psychiatrist', 'Psychiatrist')], default='Therapist', max_length=200),
        ),
    ]
