# Generated by Django 3.2.19 on 2023-10-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0036_condition_therapist_therapistcategory_therapisttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='therapist_category',
            field=models.CharField(choices=[('Cognitive Behavioral Therapy (CBT)', 'Cognitive Behavioral Therapy (CBT)'), ('Psychoanalysis or Psychodynamic', 'Psychoanalysis or Psychodynamic'), ('Therapy', 'Therapy')], default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='therapist_type',
            field=models.CharField(choices=[('Cognitive Therapy (CT)', 'Cognitive Therapy (CT)'), ('Dialectical Behavioral', 'Dialectical Behavioral'), ('Emotive Behavior Therapy', 'Emotive Behavior Therapy'), ('Cognitive Processing Therapy', 'Cognitive Processing Therapy'), ('Dream interpretation', 'Dream interpretation'), ('Free Association', 'Free Association'), ('Transference', 'Transference')], default='None', max_length=200),
        ),
    ]
