# Generated by Django 3.2.19 on 2023-10-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0037_auto_20231019_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='conditions_treated',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='therapist_type',
        ),
        migrations.RemoveField(
            model_name='therapisttype',
            name='category',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Therapist',
        ),
        migrations.DeleteModel(
            name='TherapistCategory',
        ),
        migrations.DeleteModel(
            name='TherapistType',
        ),
    ]
